#   ______             __          __
#  |  ____|            \ \        / /
#  | |__   __ _ ___ _   \ \  /\  / /_ _ _ __ _ __
#  |  __| / _` / __| | | \ \/  \/ / _` | '__| '_ \
#  | |___| (_| \__ \ |_| |\  /\  / (_| | |  | |_) |
#  |______\__,_|___/\__, | \/  \/ \__,_|_|  | .__/
#                    __/ |                  | |
#                   |___/                   |_|    by nSSj_



# below you can set the cooldown after the /warp command
# the user will be teleported after the cooldown, and he'll not be able to type it again until the end of the cooldown

cooldown: 5

# cancel the teleport after the /warp command if the user moves

cancelTpOnMove: true

# require permission for every warp (easywarp.warp.warpname)

requireWarpPermission: false

# plugin messages (use the § character for colors, see https://minecraft.tools/en/color-code.php)
# you can use the %warp% and %cooldown% variables where they're used, they're optional anyway

messages:
  warpWrongSyntax: "§eSpecify a warp to reach."
  warpDoNotExist: "§cWarp §e%warp% §cdoes not exist."
  warpNoPermission: "§cYou can't go to warp §e%warp%§c."
  teleportCooldown: "§cYou have to wait %cooldown% seconds before teleporting to §e%warp%§c."
  teleportInProgress: "§aDon't move, you will be teleported to §e%warp% §ain %cooldown% seconds."
  teleportSuccessfully: "§aYou reached §e%warp%§a."
  teleportCancelled: "§cTeleport to warp §e%warp% §ccancelled."
  setWarpWrongSyntax: "§cSpecify the name of the warp to create."
  warpAlreadyExists: "§cThe warp §e%warp% §calready exists."
  warpCreated: "§aThe warp §e%warp% §ahas been created."
  delWarpWrongSyntax: "§cSpecify the name of the warp to delete."
  warpDeleted: "§aWarp §e%warp% §ahas been deleted."
  listWarpWrongSyntax: "§cYou can't do that."
  noWarps: "§cThere aren't warps to reach."
  listWarp: "§dHere is a list of all the warps:"
  listWarpItem: " §d- §e%warp%"
